server:
  port: 8080

spring:
  application:
    name: diagram-service

eureka:
   client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    region: default
    registryFetchIntervalSeconds: 5