server:
  port: 8066

spring:
  application:
    name: net-service

eureka:
   client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    region: default
    registryFetchIntervalSeconds: 5